### ISSUE TITLE
Create API Doc

### ISSUE THREAD

**Issue by spottedmahn** [AbhitejJohn/testfxex#11]
I think it would very useful to expose and API doc / md page 📃.  What does this extension library offer 🤔?

**Comment by AbhitejJohn** [comment]
Haven't polished this out very much. It's been a while - I can potentially try and pull that list out from the xml docs and share that in an md.

**Comment by spottedmahn** [comment]
This should do the trick: [Gist - Generates Markdown From VisualStudio XML documentation files](https://gist.github.com/formix/515d3d11ee7c1c252f92).

[Sample MD output](https://github.com/formix/MegaCityOne/blob/master/MegaCityOne/doc/api.md).

[Source](https://stackoverflow.com/a/28653158/185123).

Thoughts 💭?

**Comment by AbhitejJohn** [comment]
Excellent. Thanks. Updated the docs.

**Comment by spottedmahn** [comment]
Nice, thanks 🙏 @AbhitejJohn!
